import { Inter } from "next/font/google";
import "./globals.css";
import { Gothic_A1 } from "next/font/google";
const gothic_a1 = Gothic_A1({subsets: ["latin"], weight: ["900"]})
export const metadata = {
  title: "CursorBlend",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gothic_a1.className}>{children}</body>
    </html>
  );
}
